# Makefile 

all:
	(cd Data_Rec; make -f Makefile)
	(cd NoahLand; make -f Makefile)
	(cp NoahLand/*/*.mod mod; cp NoahLand/Run/librtland.a lib/libland.a)
	(cd Routing; make -f Makefile)
	(cd NDHMS_drv;   make -f Makefile)
	(cd Main; make -f Makefile)

clean:
	(cd Data_Rec; make -f Makefile clean)
	(cd NDHMS_drv; make -f Makefile clean)
	(cd Main;       make -f Makefile clean)
	(cd Routing;    make -f Makefile clean)
	(cd NoahLand; make -f Makefile clean)
	(rm -f lib/*.a mod/*.mod)
