# Makefile 

all:
	(cd MPP; make -f Makefile)
	(cd Noah_code; make -f Makefile)
	(cd WRF_code;  make -f Makefile)
	(cd IO_code;   make -f Makefile)
	(cd Run;       make -f Makefile.rtland )

clean:
	(cd MPP; make -f Makefile clean)
	(cd Noah_code; make -f Makefile clean)
	(cd WRF_code;  make -f Makefile clean)
	(cd IO_code;   make -f Makefile clean)
	(cd Run;       make -f Makefile.rtland clean)

