#!/bin/sh

#### UNIX Script Documentation Block
#
# Script Name:  JWRF_HYDRO_TEST
####

module load prod_util
date

export PS4='$SECONDS + '
set -xa

######################################################
# Default to NCO production run environment
#######################################################
export RUN_ENVIR=${RUN_ENVIR:-prod}
export SENDECF=${SENDECF:-YES}

##########################
# Specify NET and RUN Name 
##########################
export NET=wrf_hydro
export RUN=wrf_hydro

###############################################################
# This block can be modified for different Production test
# environment. This is used for operational testings
###############################################################
if [ "$RUN_ENVIR" = prod -a $envir != prod ]; then  #for PROD
  export jlogfile=${jlogfile:-/ohd/noscrub/$LOGNAME/com/logs/jlogfile.${job}.$$}
  export SENDDBN=NO #NO for developers
fi


# #### 06/09/15 #####################################
# SET WRF_HYDRO TESTING SCRIPT PROCESSING VARIABLES
# ###################################################

###############################
# obtain unique process id (pid)
################################
export pid=$$
export cycle=t${cyc}z

########################################################
# Make working directory and file To Log Msgs 
########################################################

export WORKDIR=/ohd/noscrub/$LOGNAME/com/${job}

if [ -d $WORKDIR ]; then
  rm -rf $WORKDIR/*
else
  mkdir -p ${WORKDIR}
fi

cd ${WORKDIR}

####################################
# Determine Job Output Name on System
####################################
export outid="LSF${job}"
export jobid="${outid}.${pid}"
export pgmout="OUTPUT.${pid}"
export MP_PULSE=0

####################################
# SENDECF  - Flag Events on ECF
# SENDCOM  - Copy files to /com directory
####################################

export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDCOM=${SENDCOM:-YES}

if [ "${PARAFLAG}" = "YES" ]
then
  export SENDCOM=YES
  export SENDECF=NO 
fi

####################################
# Specify Application Areas
####################################
#export HOMEwrf_hydro=${HOMEwrf_hydro:-${NWROOT:?}/${NET}.${model_ver}}
export HOMEwrf_hydro=${HOMEwrf_hydro:-${applicationDir}/nw${envir}/${NET}.${model_ver}}
export EXECwrf_hydro=${EXECwrf_hydro:-${HOMEwrf_hydro}/exec}
export FIXwrf_hydro=${FIXwrf_hydro:-${HOMEwrf_hydro}/fix}
export USHwrf_hydro=${USHwrf_hydro:-${HOMEwrf_hydro}/ush}
export PARMwrf_hydro=${PARMwrf_hydro:-${HOMEwrf_hydro}/parm}
export EXECode=${EXECode:-${CODEwrf_hydro}/exec}


###################################
# Set up the UTILITIES
###################################
export utilscript=${utilscript:-/nwprod/util/ush}
export utilexec=${utilexec:-/nwprod/util/exec}


# Run setup to initialize working directory and utility scripts
sh $utilscript/setup.sh

# Set PDY
sh $utilscript/setpdy.sh
. ./PDY
export COMDIR=/ohd/noscrub/$LOGNAME/com/
export COMINforcing=$COMDIR/forcing
export COMINdomain=$COMDIR/DOMAIN

export COMIN=$COMDIR/${NET}/${envir}/${RUN}.${PDY}
export COMOUT=$COMDIR/${NET}/${envir}/${RUN}.${PDY}
export LOGSDIR=$COMDIR/logs
#export PCOM=/ohd/noscrub/$LOGNAME/pcom/{NET}

#if [ "$SENDCOM" = "YES"]; then
   mkdir -m 775 -p $COMOUT $COMIN $LOGSDIR #$PCOM 
#fi

####################################
# File To Log Msgs
####################################
export jlogfile=$LOGSDIR/jlogfile.${job}.$$

######################################################
# Set the mpi run command appropriate for the job card
######################################################

export mpicmd="mpirun -genvall -n $LSB_DJOB_NUMPROC -machinefile $LSB_DJOB_HOSTFILE"

env   

########################################################
# Execute the script.
########################################################
${HOMEwrf_hydro}/scripts/exwrf_hydro_test.sh.ecf

date
