.. vim: syntax=rst
.. include:: meta.rest

.. image:: media/wrfhydro-banner.png
    :align: center

=========================================================
The NCAR WRF-Hydro® Modeling System Technical Description
=========================================================
.. rst-class:: center

    | Version |version_long|
    |
    | Originally Created:
    | April 14, 2013
    |
    | Updated:
    | October 17, 2024

Until further notice, please cite the WRF-Hydro® modeling system as
follows:

Gochis, D.J., M. Barlage, R. Cabell, M. Casali, A. Dugger, T. Eidhammer,
K. FitzGerald, M. McAllister, J. McCreight, A. McCluskey, A. RafieeiNasab,
S. Rasmussen, L. Read, K. Sampson, D. Yates, Y. Zhang (2024).
*The WRF-Hydro® Modeling System Technical Description,* (Version 5.4).
NCAR Technical Note. 107 pages. Available online at:
https://wrf-hydro.readthedocs.io/en/latest/

.. rubric:: FORWARD

This Technical Description describes the WRF-Hydro® model coupling
architecture and physics options, released in Version 5.4 in Oct. 2024.
As the WRF-Hydro® modeling system is developed further, this document
will be continuously enhanced and updated. Please send feedback to
wrfhydro@ucar.edu.

.. rubric:: Prepared by:

David Gochis, Michael Barlage, Ryan Cabell, Matt Casali, Aubrey Dugger, Trude
Eidhammer, Katelyn FitzGerald, Molly McAllister, James McCreight, Alyssa
McCluskey, Arezoo RafieeiNasab, Soren Rasmussen, Laura Read, Kevin Sampson,
David Yates, and Yongxin Zhang

.. rubric:: Special Acknowledgments:

Development of the NCAR WRF-Hydro system has been significantly enhanced
through numerous collaborations. The following persons are graciously
thanked for their contributions to this effort:

John McHenry and Carlie Coats, Baron Advanced Meteorological Services

Martyn Clark and Fei Chen, National Center for Atmospheric Research

Zong-Liang Yang, Cedric David, Peirong Lin and David Maidment of the
University of Texas at Austin

Harald Kunstmann, Benjamin Fersch and Thomas Rummler of Karlsruhe
Institute of Technology, Garmisch-Partenkirchen, Germany

Alfonso Senatore, University of Calabria, Cosenza, Italy

Brian Cosgrove, Ed Clark, Fernando Salas, Trey Flowers, Xia Feng,
Yuqiong Liu, Nels Frazier,

Fred Ogden, Dave Mattern, Don Johnson, and Tom Graziano of the National
Oceanic and Atmospheric Administration Office of Water Prediction

Ismail Yucel, Middle East Technical University, Ankara, Turkey

Erick Fredj, The Jerusalem College of Technology, Jerusalem, Israel

Amir Givati, Surface water and Hydrometeorology Department, Israeli
Hydrological Service, Jerusalem.

Antonio Parodi, Fondazione CIMA - Centro Internazionale in Monitoraggio
Ambientale, Savona, Italy

Blair Greimann, Sedimentation and Hydraulics section, U.S. Bureau of
Reclamation

Z George Xue and Dongxiao Yin, Louisiana State University

Funding support for the development and application of the WRF-Hydro®
modeling system has been provided by:

The National Science Foundation and the National Center for Atmospheric
Research

The U.S. National Weather Service

The Colorado Water Conservation Board

Baron Advanced Meteorological Services

National Aeronautics and Space Administration (NASA)

National Oceanic and Atmospheric Administration (NOAA) Office of Water
Prediction (OWP)


.. toctree::
    :hidden:

    Preface / Acknowledgements <self>
    introduction
    model-code-config
    model-physics
    nudging
    model-inputs-preproc
    model-outputs
    references
    appendices
