all:
	(cd ..;make)

clean:
	(cd ..; make clean)
mpp:
	(cd ..;make -f Makefile.mpp)
rtland:
	(cd ..;cp macros.mpp macros;make -f Makefile.rtland)
cleanmpp:
	(rm Noah_wrfdriver_beta_mpp;cd ..; make clean -f Makefile.mpp)
