# Makefile 
#
#INCLUDES=
.SUFFIXES:
.SUFFIXES: .o .f

include ../macros

OBJS = \
	../Noah_code/module_Noahlsm.o \
	../Noah_code/module_Noahlsm_param_init_rt.o \
	../Noah_code/module_Noahlsm_utility_rt.o \
	../Noah_code/module_date_utilities_rt.o

WRFCODE_OBJS = \
	../IO_code/module_RTLAND.o \
	../IO_code/module_Noahlsm_wrf_input_rt.o \
	../IO_code/module_Noah_distr_routing.o \
	../IO_code/module_Noah_channel_routing.o \
	../IO_code/module_Noah_chan_param_init_rt.o \
	../WRF_code/module_sf_noahlsm_rt.o \
	../Noah_code/module_model_constants_rt.o \
	../Noah_code/module_Noahlsm_utility_rt.o \
	../Noah_code/module_date_utilities_rt.o \
 	../IO_code/module_Noah_gw_baseflow.o
#	../IO_code/drive_rtland.o \
#	../MPP/mpp_land.o \
#	../MPP/CPL_WRF.o \



all:	librtland.a	

librtland.a: $(WRFCODE_OBJS)
	@echo ""
	ar ru $(@) $(WRFCODE_OBJS)
	@echo ""

#$(MODFLAG)../Noah_code 
#

# This command cleans up
clean:
	rm -f *~ $(CMD) lib*.a

